openapi: 3.0.0
info:
  contact:
    email: MJoachimiak@lbl.gov
    url: 'http://smartbag-hpotomondo.ncats.io/apidocs'
  description: A Bicluster API for HP Ontology to Mondo bicluster analysis.
  title: HPO to Mondo Bicluster API
  version: "v1.0-oas3"
paths:
  '/HPO_to_MONDO_bicluster/{bicluster}/':
    get:
      parameters:
        - in: path
          name: bicluster
          required: true
          x-requestTemplate:
            - template: '/HPO_to_MONDO_bicluster/{{ input }}'
              valueType: 'http://schema.org/name'
          x-valueType:
            - 'http://schema.org/name'
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /HPO_to_MONDO_metadata
          x-responseValueType:
            - path: bicluster
              valueType: 'http://schema.org/name'
            - path: hpo
              valueType: 'http://identifiers.org/hp/'
            - path: bicluster_score
              valueType: 'http://schema.org/name'
            - path: bicluster_mean
              valueType: 'http://schema.org/name'
            - path: hpo_bicluster_cor
              valueType: 'http://schema.org/name'
            - path: mondo_list
              valueType: 'http://schema.org/name'
      summary: Get row by bicluster
  '/HPO_to_MONDO_bicluster_mean/{bicluster_mean}/':
    get:
      parameters:
        - in: path
          name: bicluster_mean
          required: true
          x-requestTemplate:
            - template: '/HPO_to_MONDO_bicluster_mean/{{ input }}'
              valueType: 'http://schema.org/name'
          x-valueType:
            - 'http://schema.org/name'
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /HPO_to_MONDO_metadata
          x-responseValueType:
            - path: bicluster
              valueType: 'http://schema.org/name'
            - path: hpo
              valueType: 'http://identifiers.org/hp/'
            - path: bicluster_score
              valueType: 'http://schema.org/name'
            - path: bicluster_mean
              valueType: 'http://schema.org/name'
            - path: hpo_bicluster_cor
              valueType: 'http://schema.org/name'
            - path: mondo_list
              valueType: 'http://schema.org/name'
      summary: Get row by bicluster_mean
  '/HPO_to_MONDO_bicluster_score/{bicluster_score}/':
    get:
      parameters:
        - in: path
          name: bicluster_score
          required: true
          x-requestTemplate:
            - template: '/HPO_to_MONDO_bicluster_score/{{ input }}'
              valueType: 'http://schema.org/name'
          x-valueType:
            - 'http://schema.org/name'
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /HPO_to_MONDO_metadata
          x-responseValueType:
            - path: bicluster
              valueType: 'http://schema.org/name'
            - path: hpo
              valueType: 'http://identifiers.org/hp/'
            - path: bicluster_score
              valueType: 'http://schema.org/name'
            - path: bicluster_mean
              valueType: 'http://schema.org/name'
            - path: hpo_bicluster_cor
              valueType: 'http://schema.org/name'
            - path: mondo_list
              valueType: 'http://schema.org/name'
      summary: Get row by bicluster_score
  /HPO_to_MONDO_examples/:
    get:
      responses:
        '200':
          description: ...
      summary: Get a few example rows
  '/HPO_to_MONDO_hpo/{hpo}/':
    get:
      parameters:
        - in: path
          name: hpo
          required: true
          x-requestTemplate:
            - template: '/HPO_to_MONDO_hpo/{{ input }}'
              valueType: 'http://identifiers.org/hp/'
          x-valueType:
            - 'http://identifiers.org/hp/'
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /HPO_to_MONDO_metadata
          x-responseValueType:
            - path: bicluster
              valueType: 'http://schema.org/name'
            - path: hpo
              valueType: 'http://identifiers.org/hp/'
            - path: bicluster_score
              valueType: 'http://schema.org/name'
            - path: bicluster_mean
              valueType: 'http://schema.org/name'
            - path: hpo_bicluster_cor
              valueType: 'http://schema.org/name'
            - path: mondo_list
              valueType: 'http://schema.org/name'
      summary: Get row by hpo
  '/HPO_to_MONDO_hpo_bicluster_cor/{hpo_bicluster_cor}/':
    get:
      parameters:
        - in: path
          name: hpo_bicluster_cor
          required: true
          x-requestTemplate:
            - template: '/HPO_to_MONDO_hpo_bicluster_cor/{{ input }}'
              valueType: 'http://schema.org/name'
          x-valueType:
            - 'http://schema.org/name'
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /HPO_to_MONDO_metadata
          x-responseValueType:
            - path: bicluster
              valueType: 'http://schema.org/name'
            - path: hpo
              valueType: 'http://identifiers.org/hp/'
            - path: bicluster_score
              valueType: 'http://schema.org/name'
            - path: bicluster_mean
              valueType: 'http://schema.org/name'
            - path: hpo_bicluster_cor
              valueType: 'http://schema.org/name'
            - path: mondo_list
              valueType: 'http://schema.org/name'
      summary: Get row by hpo_bicluster_cor
  /HPO_to_MONDO_metadata/:
    get:
      responses:
        '200':
          description: ...
      summary: 'Get service metadata '
  '/HPO_to_MONDO_mondo_list/{mondo_list}/':
    get:
      parameters:
        - in: path
          name: mondo_list
          required: true
          x-requestTemplate:
            - template: '/HPO_to_MONDO_mondo_list/{{ input }}'
              valueType: 'http://schema.org/name'
          x-valueType:
            - 'http://schema.org/name'
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /HPO_to_MONDO_metadata
          x-responseValueType:
            - path: bicluster
              valueType: 'http://schema.org/name'
            - path: hpo
              valueType: 'http://identifiers.org/hp/'
            - path: bicluster_score
              valueType: 'http://schema.org/name'
            - path: bicluster_mean
              valueType: 'http://schema.org/name'
            - path: hpo_bicluster_cor
              valueType: 'http://schema.org/name'
            - path: mondo_list
              valueType: 'http://schema.org/name'
      summary: Get row by mondo_list
  /specification/:
    get:
      responses:
        '200':
          description: ...
      summary: Get the smartapi specification.