openapi: 3.0.0
info:
  contact:
    email: scox@renci.org
    url: 'http://www.renci.org'
  description: Bicluster API
  termsOfService: 'http://x.org/terms'
  title: BiCluster API
  version: "0.0.2-oas3"
paths:
  '/BiCluster_column_enrich/{column_enrich}/':
    get:
      parameters:
        - in: path
          name: column_enrich
          required: true
          x-requestTemplate:
            - template: '/BiCluster_column_enrich/{{ input }}'
              valueType: None
          x-valueType:
            - None
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /BiCluster_metadata
          x-responseValueType:
            - path: rank
              valueType: None
            - path: gene
              valueType: None
            - path: score
              valueType: None
            - path: mean
              valueType: None
            - path: correlation
              valueType: None
            - path: column_enrich
              valueType: None
            - path: column_enrich_MONDO
              valueType: None
            - path: column_enrich_UBERON
              valueType: None
            - path: column_enrich_DOID
              valueType: None
            - path: column_enrich_NCIT
              valueType: None
      summary: Get row by column_enrich
  '/BiCluster_column_enrich_DOID/{column_enrich_DOID}/':
    get:
      parameters:
        - in: path
          name: column_enrich_DOID
          required: true
          x-requestTemplate:
            - template: '/BiCluster_column_enrich_DOID/{{ input }}'
              valueType: None
          x-valueType:
            - None
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /BiCluster_metadata
          x-responseValueType:
            - path: rank
              valueType: None
            - path: gene
              valueType: None
            - path: score
              valueType: None
            - path: mean
              valueType: None
            - path: correlation
              valueType: None
            - path: column_enrich
              valueType: None
            - path: column_enrich_MONDO
              valueType: None
            - path: column_enrich_UBERON
              valueType: None
            - path: column_enrich_DOID
              valueType: None
            - path: column_enrich_NCIT
              valueType: None
      summary: Get row by column_enrich_DOID
  '/BiCluster_column_enrich_MONDO/{column_enrich_MONDO}/':
    get:
      parameters:
        - in: path
          name: column_enrich_MONDO
          required: true
          x-requestTemplate:
            - template: '/BiCluster_column_enrich_MONDO/{{ input }}'
              valueType: None
          x-valueType:
            - None
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /BiCluster_metadata
          x-responseValueType:
            - path: rank
              valueType: None
            - path: gene
              valueType: None
            - path: score
              valueType: None
            - path: mean
              valueType: None
            - path: correlation
              valueType: None
            - path: column_enrich
              valueType: None
            - path: column_enrich_MONDO
              valueType: None
            - path: column_enrich_UBERON
              valueType: None
            - path: column_enrich_DOID
              valueType: None
            - path: column_enrich_NCIT
              valueType: None
      summary: Get row by column_enrich_MONDO
  '/BiCluster_column_enrich_NCIT/{column_enrich_NCIT}/':
    get:
      parameters:
        - in: path
          name: column_enrich_NCIT
          required: true
          x-requestTemplate:
            - template: '/BiCluster_column_enrich_NCIT/{{ input }}'
              valueType: None
          x-valueType:
            - None
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /BiCluster_metadata
          x-responseValueType:
            - path: rank
              valueType: None
            - path: gene
              valueType: None
            - path: score
              valueType: None
            - path: mean
              valueType: None
            - path: correlation
              valueType: None
            - path: column_enrich
              valueType: None
            - path: column_enrich_MONDO
              valueType: None
            - path: column_enrich_UBERON
              valueType: None
            - path: column_enrich_DOID
              valueType: None
            - path: column_enrich_NCIT
              valueType: None
      summary: Get row by column_enrich_NCIT
  '/BiCluster_column_enrich_UBERON/{column_enrich_UBERON}/':
    get:
      parameters:
        - in: path
          name: column_enrich_UBERON
          required: true
          x-requestTemplate:
            - template: '/BiCluster_column_enrich_UBERON/{{ input }}'
              valueType: None
          x-valueType:
            - None
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /BiCluster_metadata
          x-responseValueType:
            - path: rank
              valueType: None
            - path: gene
              valueType: None
            - path: score
              valueType: None
            - path: mean
              valueType: None
            - path: correlation
              valueType: None
            - path: column_enrich
              valueType: None
            - path: column_enrich_MONDO
              valueType: None
            - path: column_enrich_UBERON
              valueType: None
            - path: column_enrich_DOID
              valueType: None
            - path: column_enrich_NCIT
              valueType: None
      summary: Get row by column_enrich_UBERON
  '/BiCluster_correlation/{correlation}/':
    get:
      parameters:
        - in: path
          name: correlation
          required: true
          x-requestTemplate:
            - template: '/BiCluster_correlation/{{ input }}'
              valueType: None
          x-valueType:
            - None
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /BiCluster_metadata
          x-responseValueType:
            - path: rank
              valueType: None
            - path: gene
              valueType: None
            - path: score
              valueType: None
            - path: mean
              valueType: None
            - path: correlation
              valueType: None
            - path: column_enrich
              valueType: None
            - path: column_enrich_MONDO
              valueType: None
            - path: column_enrich_UBERON
              valueType: None
            - path: column_enrich_DOID
              valueType: None
            - path: column_enrich_NCIT
              valueType: None
      summary: Get row by correlation
  /BiCluster_examples/:
    get:
      responses:
        '200':
          description: ...
      summary: Get a few example rows
  '/BiCluster_gene/{gene}/':
    get:
      parameters:
        - in: path
          name: gene
          required: true
          x-requestTemplate:
            - template: '/BiCluster_gene/{{ input }}'
              valueType: None
          x-valueType:
            - None
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /BiCluster_metadata
          x-responseValueType:
            - path: rank
              valueType: None
            - path: gene
              valueType: None
            - path: score
              valueType: None
            - path: mean
              valueType: None
            - path: correlation
              valueType: None
            - path: column_enrich
              valueType: None
            - path: column_enrich_MONDO
              valueType: None
            - path: column_enrich_UBERON
              valueType: None
            - path: column_enrich_DOID
              valueType: None
            - path: column_enrich_NCIT
              valueType: None
      summary: Get row by gene
  '/BiCluster_mean/{mean}/':
    get:
      parameters:
        - in: path
          name: mean
          required: true
          x-requestTemplate:
            - template: '/BiCluster_mean/{{ input }}'
              valueType: None
          x-valueType:
            - None
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /BiCluster_metadata
          x-responseValueType:
            - path: rank
              valueType: None
            - path: gene
              valueType: None
            - path: score
              valueType: None
            - path: mean
              valueType: None
            - path: correlation
              valueType: None
            - path: column_enrich
              valueType: None
            - path: column_enrich_MONDO
              valueType: None
            - path: column_enrich_UBERON
              valueType: None
            - path: column_enrich_DOID
              valueType: None
            - path: column_enrich_NCIT
              valueType: None
      summary: Get row by mean
  /BiCluster_metadata/:
    get:
      responses:
        '200':
          description: ...
      summary: 'Get service metadata '
  '/BiCluster_rank/{rank}/':
    get:
      parameters:
        - in: path
          name: rank
          required: true
          x-requestTemplate:
            - template: '/BiCluster_rank/{{ input }}'
              valueType: None
          x-valueType:
            - None
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /BiCluster_metadata
          x-responseValueType:
            - path: rank
              valueType: None
            - path: gene
              valueType: None
            - path: score
              valueType: None
            - path: mean
              valueType: None
            - path: correlation
              valueType: None
            - path: column_enrich
              valueType: None
            - path: column_enrich_MONDO
              valueType: None
            - path: column_enrich_UBERON
              valueType: None
            - path: column_enrich_DOID
              valueType: None
            - path: column_enrich_NCIT
              valueType: None
      summary: Get row by rank
  '/BiCluster_score/{score}/':
    get:
      parameters:
        - in: path
          name: score
          required: true
          x-requestTemplate:
            - template: '/BiCluster_score/{{ input }}'
              valueType: None
          x-valueType:
            - None
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /BiCluster_metadata
          x-responseValueType:
            - path: rank
              valueType: None
            - path: gene
              valueType: None
            - path: score
              valueType: None
            - path: mean
              valueType: None
            - path: correlation
              valueType: None
            - path: column_enrich
              valueType: None
            - path: column_enrich_MONDO
              valueType: None
            - path: column_enrich_UBERON
              valueType: None
            - path: column_enrich_DOID
              valueType: None
            - path: column_enrich_NCIT
              valueType: None
      summary: Get row by score
  /specification/:
    get:
      responses:
        '200':
          description: ...
      summary: Get the smartapi specification.