openapi: 3.0.0
info:
  contact:
    email: MJoachimiak@lbl.gov
    url: 'https://smartbag-crispridepmap.ncats.io/apidocs'
  description: A Bicluster API for DepMap bicluster analysis.
  title: DepMap BiCluster API
  version: "0.0.2-oas3"
paths:
  '/biclusters_DepMap_gene_to_cellline_v1_all_col_labels/{all_col_labels}/':
    get:
      parameters:
        - in: path
          name: all_col_labels
          required: true
          x-requestTemplate:
            - template: >-
                /biclusters_DepMap_gene_to_cellline_v1_all_col_labels/{{ input
                }}
              valueType: 'http://schema.org/name'
          x-valueType:
            - 'http://schema.org/name'
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /biclusters_DepMap_gene_to_cellline_v1_metadata
          x-responseValueType:
            - path: bicluster
              valueType: 'http://schema.org/name'
            - path: gene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: bicluster_score
              valueType: 'http://schema.org/name'
            - path: bicluster_mean
              valueType: 'http://schema.org/name'
            - path: gene_bicluster_cor
              valueType: 'http://schema.org/name'
            - path: row_enrich
              valueType: 'http://identifiers.org/go/'
            - path: all_col_labels
              valueType: 'http://schema.org/name'
      summary: Get row by all_col_labels
  '/biclusters_DepMap_gene_to_cellline_v1_bicluster/{bicluster}/':
    get:
      parameters:
        - in: path
          name: bicluster
          required: true
          x-requestTemplate:
            - template: '/biclusters_DepMap_gene_to_cellline_v1_bicluster/{{ input }}'
              valueType: 'http://schema.org/name'
          x-valueType:
            - 'http://schema.org/name'
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /biclusters_DepMap_gene_to_cellline_v1_metadata
          x-responseValueType:
            - path: bicluster
              valueType: 'http://schema.org/name'
            - path: gene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: bicluster_score
              valueType: 'http://schema.org/name'
            - path: bicluster_mean
              valueType: 'http://schema.org/name'
            - path: gene_bicluster_cor
              valueType: 'http://schema.org/name'
            - path: row_enrich
              valueType: 'http://identifiers.org/go/'
            - path: all_col_labels
              valueType: 'http://schema.org/name'
      summary: Get row by bicluster
  '/biclusters_DepMap_gene_to_cellline_v1_bicluster_mean/{bicluster_mean}/':
    get:
      parameters:
        - in: path
          name: bicluster_mean
          required: true
          x-requestTemplate:
            - template: >-
                /biclusters_DepMap_gene_to_cellline_v1_bicluster_mean/{{ input
                }}
              valueType: 'http://schema.org/name'
          x-valueType:
            - 'http://schema.org/name'
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /biclusters_DepMap_gene_to_cellline_v1_metadata
          x-responseValueType:
            - path: bicluster
              valueType: 'http://schema.org/name'
            - path: gene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: bicluster_score
              valueType: 'http://schema.org/name'
            - path: bicluster_mean
              valueType: 'http://schema.org/name'
            - path: gene_bicluster_cor
              valueType: 'http://schema.org/name'
            - path: row_enrich
              valueType: 'http://identifiers.org/go/'
            - path: all_col_labels
              valueType: 'http://schema.org/name'
      summary: Get row by bicluster_mean
  '/biclusters_DepMap_gene_to_cellline_v1_bicluster_score/{bicluster_score}/':
    get:
      parameters:
        - in: path
          name: bicluster_score
          required: true
          x-requestTemplate:
            - template: >-
                /biclusters_DepMap_gene_to_cellline_v1_bicluster_score/{{ input
                }}
              valueType: 'http://schema.org/name'
          x-valueType:
            - 'http://schema.org/name'
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /biclusters_DepMap_gene_to_cellline_v1_metadata
          x-responseValueType:
            - path: bicluster
              valueType: 'http://schema.org/name'
            - path: gene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: bicluster_score
              valueType: 'http://schema.org/name'
            - path: bicluster_mean
              valueType: 'http://schema.org/name'
            - path: gene_bicluster_cor
              valueType: 'http://schema.org/name'
            - path: row_enrich
              valueType: 'http://identifiers.org/go/'
            - path: all_col_labels
              valueType: 'http://schema.org/name'
      summary: Get row by bicluster_score
  /biclusters_DepMap_gene_to_cellline_v1_examples/:
    get:
      responses:
        '200':
          description: ...
      summary: Get a few example rows
  '/biclusters_DepMap_gene_to_cellline_v1_gene/{gene}/':
    get:
      parameters:
        - in: path
          name: gene
          required: true
          x-requestTemplate:
            - template: '/biclusters_DepMap_gene_to_cellline_v1_gene/{{ input }}'
              valueType: 'http://identifiers.org/ncbigene/'
          x-valueType:
            - 'http://identifiers.org/ncbigene/'
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /biclusters_DepMap_gene_to_cellline_v1_metadata
          x-responseValueType:
            - path: bicluster
              valueType: 'http://schema.org/name'
            - path: gene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: bicluster_score
              valueType: 'http://schema.org/name'
            - path: bicluster_mean
              valueType: 'http://schema.org/name'
            - path: gene_bicluster_cor
              valueType: 'http://schema.org/name'
            - path: row_enrich
              valueType: 'http://identifiers.org/go/'
            - path: all_col_labels
              valueType: 'http://schema.org/name'
      summary: Get row by gene
  '/biclusters_DepMap_gene_to_cellline_v1_gene_bicluster_cor/{gene_bicluster_cor}/':
    get:
      parameters:
        - in: path
          name: gene_bicluster_cor
          required: true
          x-requestTemplate:
            - template: >-
                /biclusters_DepMap_gene_to_cellline_v1_gene_bicluster_cor/{{
                input }}
              valueType: 'http://schema.org/name'
          x-valueType:
            - 'http://schema.org/name'
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /biclusters_DepMap_gene_to_cellline_v1_metadata
          x-responseValueType:
            - path: bicluster
              valueType: 'http://schema.org/name'
            - path: gene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: bicluster_score
              valueType: 'http://schema.org/name'
            - path: bicluster_mean
              valueType: 'http://schema.org/name'
            - path: gene_bicluster_cor
              valueType: 'http://schema.org/name'
            - path: row_enrich
              valueType: 'http://identifiers.org/go/'
            - path: all_col_labels
              valueType: 'http://schema.org/name'
      summary: Get row by gene_bicluster_cor
  /biclusters_DepMap_gene_to_cellline_v1_metadata/:
    get:
      responses:
        '200':
          description: ...
      summary: 'Get service metadata '
  '/biclusters_DepMap_gene_to_cellline_v1_row_enrich/{row_enrich}/':
    get:
      parameters:
        - in: path
          name: row_enrich
          required: true
          x-requestTemplate:
            - template: '/biclusters_DepMap_gene_to_cellline_v1_row_enrich/{{ input }}'
              valueType: 'http://identifiers.org/go/'
          x-valueType:
            - 'http://identifiers.org/go/'
          schema:
            type: string
        - in: query
          name: include_similar
          x-requestTemplate:
            - valueType: 'http://schema.org/boolean'
          x-valueType:
            - 'http://schema.org/boolean'
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: success
          x-JSONLDContext: /biclusters_DepMap_gene_to_cellline_v1_metadata
          x-responseValueType:
            - path: bicluster
              valueType: 'http://schema.org/name'
            - path: gene
              valueType: 'http://identifiers.org/ncbigene/'
            - path: bicluster_score
              valueType: 'http://schema.org/name'
            - path: bicluster_mean
              valueType: 'http://schema.org/name'
            - path: gene_bicluster_cor
              valueType: 'http://schema.org/name'
            - path: row_enrich
              valueType: 'http://identifiers.org/go/'
            - path: all_col_labels
              valueType: 'http://schema.org/name'
      summary: Get row by row_enrich
  /specification/:
    get:
      responses:
        '200':
          description: ...
      summary: Get the smartapi specification.