openapi: '3.0.0'
info:
  version: '1.0'
  title: COHD API
  description: >-
    The COHD API
  termsOfService: http://www.cohd.org
  contact:
    name: cohd help desk
    x-role: responsible developer
    email: help@cohd.org
servers:
  - url: 'http://tr-kp-clinical.ncats.io/api'
    description: 'Production server'
tags:
  - name: translator1
  - name: disease
  - name: chemical

paths:
  '/association/chiSquare':
    get:
      summary: 'retrieve associated concept data'
      parameters:
        - name: dataset_id
          in: query
          description: >-
            the dataset id
          required: true
          example: 1
          schema:
            type: integer
        - name: concept_id_1
          in: query
          description: >-
            the COHD concept id
          required: true
          example: "441554"
          schema:
            type: string
        - name: domain
          in: query
          description: >-
            the input type
          required: true
          example: "Drug"
          schema:
            type: string
      responses:
        '200':
          description: 'A COHD concept object'
      x-bte-kgs-operations:
      - $ref: '#/components/x-bte-kgs-operations/disease-disease'
      - $ref: '#/components/x-bte-kgs-operations/disease-chemical'    
      - $ref: '#/components/x-bte-kgs-operations/chemical-disease'  
components:
  x-bte-kgs-operations:
    disease-disease:
    - inputs:
      - id: OMOP
        semantic: Disease
      outputs:
      - id: OMOP
        semantic: Disease
      predicate: correlated_with
      parameters:
        dataset_id: 3
        concept_id_1: "{inputs[0]}"
        domain: Condition
      supportBatch: false
      response_mapping:
        $ref: '#/components/x-bte-response-mapping/omop'
    disease-chemical:
    - inputs:
      - id: OMOP
        semantic: Disease
      outputs:
      - id: OMOP
        semantic: ChemicalSubstance
      predicate: correlated_with
      parameters:
        dataset_id: 3
        concept_id_1: "{inputs[0]}"
        domain: Drug
      supportBatch: false
      response_mapping:
        $ref: '#/components/x-bte-response-mapping/omop'
    chemical-disease:
    - outputs:
      - id: OMOP
        semantic: Disease
      inputs:
      - id: OMOP
        semantic: ChemicalSubstance
      predicate: correlated_with
      parameters:
        dataset_id: 3
        concept_id_1: "{inputs[0]}"
        domain: Condition
      supportBatch: false
      response_mapping:
        $ref: '#/components/x-bte-response-mapping/omop'
  x-bte-response-mapping:
    omop:
      OMOP: results.concept_id_2
      adj_pvalue: results.adj_p-value
