openapi: '3.0.0'
info:
  version: '1.0'
  title: QuickGO API
  description: >-
    The QuickGO REST API provides access to key biological data from QuickGO and GOA. The services provide a unified interface to query information about ontology terms from GO (the Gene Ontology) and ECO (the Evidence & Conclusion Ontology), Gene Ontology annotations from the EBI's GOA database, and gene products (proteins from UniProt, RNA from RNAcentral and complexes from ComplexPortal). 
  termsOfService: https://www.ebi.ac.uk/QuickGO/services
  contact:
    name: pharmgkb help desk
    x-role: responsible developer
    email: help@pharmgkb.org
servers:
  - url: 'https://www.ebi.ac.uk/QuickGO/services'
    description: 'Production server'
tags:
  - name: publication
  - name: translator
paths:
  
  '/ontology/go/terms/{goid}/children':
    get:
      summary: 'retrieve the children of specified ontology terms'
      parameters:
        - name: goid
          in: path
          description: >-
            Put Gene Ontology ID here, e.g. GO:0000082
          required: true
          example: "GO:0000082"
          schema:
            type: string
      responses:
        '200':
          description: 'A gene ontolgoy annotation object'
          x-bte-response-mapping:
            $ref: '#/components/x-bte-response-mapping/hasChildren'
      x-bte-kgs-operations:
        associatedWith:
          $ref: '#/components/x-bte-kgs-operations/hasChildren'
components:
  x-bte-kgs-operations:
    hasChildren:
      inputs:
      - id: go
        semantic: MolecularActivity
      outputs:
      - id: go
        semantic: MolecularActivity
      parameters:
        goid: '{input1}'
      supportBatch: false
  x-bte-response-mapping:
    hasChildren:
      "@context": http://schema.org
      "@type": MolecularActivity
      bts:go: results.id
      bts:name: results.name
      bts:hasChildren:
        "@type": MolecularActivity
        bts:go: results.children.id
        bts:name: results.children.name
        bts:relation: results.children.relation
        "$input": bts:go
        "$source": gene ontology
